// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (
    message_id,
    type,
    filename,
    mime_type,
    size,
    storage_key,
    external_url,
    metadata,
    sort_order
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, message_id, type, filename, mime_type, size, storage_key, external_url, metadata, sort_order, created_at
`

type CreateAttachmentParams struct {
	MessageID   pgtype.UUID
	Type        string
	Filename    pgtype.Text
	MimeType    pgtype.Text
	Size        pgtype.Int8
	StorageKey  pgtype.Text
	ExternalUrl pgtype.Text
	Metadata    []byte
	SortOrder   int32
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.MessageID,
		arg.Type,
		arg.Filename,
		arg.MimeType,
		arg.Size,
		arg.StorageKey,
		arg.ExternalUrl,
		arg.Metadata,
		arg.SortOrder,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Type,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.StorageKey,
		&i.ExternalUrl,
		&i.Metadata,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByMessageID = `-- name: ListAttachmentsByMessageID :many
SELECT
    id,
    message_id,
    type,
    filename,
    mime_type,
    size,
    storage_key,
    external_url,
    metadata,
    sort_order,
    created_at
FROM attachments
WHERE message_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListAttachmentsByMessageID(ctx context.Context, messageID pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Type,
			&i.Filename,
			&i.MimeType,
			&i.Size,
			&i.StorageKey,
			&i.ExternalUrl,
			&i.Metadata,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
