// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (
    conversation_id,
    user_id
)
VALUES (
    $1,
    $2
)
`

type AddConversationMemberParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.Exec(ctx, addConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
    type
)
VALUES (
    $1
)
RETURNING id, type, created_at
`

func (q *Queries) CreateConversation(ctx context.Context, type_ string) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, type_)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, type, created_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const getConversationDetails = `-- name: GetConversationDetails :one
SELECT
    c.id,
    c.type,
    c.created_at,

    p.user_id AS participant_id,
    p.username,
    p.display_name,
    p.avatar_url

FROM conversations c

JOIN conversation_members cm_self
ON cm_self.conversation_id = c.id

JOIN conversation_members cm_other
ON cm_other.conversation_id = c.id
AND cm_other.user_id <> cm_self.user_id

JOIN profiles p
ON p.user_id = cm_other.user_id

WHERE
    c.id = $1
    AND cm_self.user_id = $2

LIMIT 1
`

type GetConversationDetailsParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetConversationDetailsRow struct {
	ID            pgtype.UUID
	Type          string
	CreatedAt     pgtype.Timestamptz
	ParticipantID pgtype.UUID
	Username      string
	DisplayName   string
	AvatarUrl     pgtype.Text
}

func (q *Queries) GetConversationDetails(ctx context.Context, arg GetConversationDetailsParams) (GetConversationDetailsRow, error) {
	row := q.db.QueryRow(ctx, getConversationDetails, arg.ID, arg.UserID)
	var i GetConversationDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.CreatedAt,
		&i.ParticipantID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const getDirectConversation = `-- name: GetDirectConversation :one
SELECT c.id, c.type, c.created_at
FROM conversations c
JOIN conversation_members cm1
    ON cm1.conversation_id = c.id
JOIN conversation_members cm2
    ON cm2.conversation_id = c.id
WHERE
    c.type = 'direct'
    AND cm1.user_id = $1
    AND cm2.user_id = $2
    AND (
        SELECT COUNT(*)
        FROM conversation_members
        WHERE conversation_id = c.id
    ) = 2
LIMIT 1
`

type GetDirectConversationParams struct {
	UserID   pgtype.UUID
	UserID_2 pgtype.UUID
}

func (q *Queries) GetDirectConversation(ctx context.Context, arg GetDirectConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getDirectConversation, arg.UserID, arg.UserID_2)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const listConversationMembers = `-- name: ListConversationMembers :many
SELECT user_id
FROM conversation_members
WHERE conversation_id = $1
`

func (q *Queries) ListConversationMembers(ctx context.Context, conversationID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT
    c.id,
    c.type,
    c.created_at,

    p.user_id       AS participant_id,
    p.username,
    p.display_name,
    p.avatar_url,

    (
        SELECT COUNT(*)
        FROM messages m
        WHERE m.conversation_id = c.id
          AND m.sender_id <> $1
          AND NOT EXISTS (
              SELECT 1
              FROM message_reads mr
              WHERE mr.message_id = m.id
                AND mr.user_id = $1
          )
    ) AS unread_count

FROM conversations c

JOIN conversation_members self
    ON self.conversation_id = c.id

JOIN conversation_members other
    ON other.conversation_id = c.id
   AND other.user_id <> self.user_id

JOIN profiles p
    ON p.user_id = other.user_id

WHERE self.user_id = $1

ORDER BY c.created_at DESC
`

type ListConversationsRow struct {
	ID            pgtype.UUID
	Type          string
	CreatedAt     pgtype.Timestamptz
	ParticipantID pgtype.UUID
	Username      string
	DisplayName   string
	AvatarUrl     pgtype.Text
	UnreadCount   int64
}

func (q *Queries) ListConversations(ctx context.Context, senderID pgtype.UUID) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.CreatedAt,
			&i.ParticipantID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
