// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (
    conversation_id,
    user_id
)
VALUES (
    $1,
    $2
)
`

type AddConversationMemberParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.Exec(ctx, addConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
    type
)
VALUES (
    $1
)
RETURNING id, type, created_at
`

func (q *Queries) CreateConversation(ctx context.Context, type_ string) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, type_)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, type, created_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const getDirectConversation = `-- name: GetDirectConversation :one
SELECT c.id, c.type, c.created_at
FROM conversations c
JOIN conversation_members cm1
    ON cm1.conversation_id = c.id
JOIN conversation_members cm2
    ON cm2.conversation_id = c.id
WHERE
    c.type = 'direct'
    AND cm1.user_id = $1
    AND cm2.user_id = $2
    AND (
        SELECT COUNT(*)
        FROM conversation_members
        WHERE conversation_id = c.id
    ) = 2
LIMIT 1
`

type GetDirectConversationParams struct {
	UserID   pgtype.UUID
	UserID_2 pgtype.UUID
}

func (q *Queries) GetDirectConversation(ctx context.Context, arg GetDirectConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getDirectConversation, arg.UserID, arg.UserID_2)
	var i Conversation
	err := row.Scan(&i.ID, &i.Type, &i.CreatedAt)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT
    c.id,
    c.type,
    c.created_at
FROM conversations c
JOIN conversation_members cm
    ON cm.conversation_id = c.id
WHERE cm.user_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) ListConversations(ctx context.Context, userID pgtype.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(&i.ID, &i.Type, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
