// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    conversation_id,
    sender_id,
    content
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, conversation_id, sender_id, content, created_at
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID
	SenderID       pgtype.UUID
	Content        string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT
    m.id,
    m.conversation_id,
    m.sender_id,
    m.content,
    m.created_at,

    p.username,
    p.display_name,
    p.avatar_url

FROM messages m

JOIN profiles p
    ON p.user_id = m.sender_id

WHERE m.id = $1
`

type GetMessageByIDRow struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	SenderID       pgtype.UUID
	Content        string
	CreatedAt      pgtype.Timestamptz
	Username       string
	DisplayName    string
	AvatarUrl      pgtype.Text
}

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS(
    SELECT 1
    FROM conversation_members
    WHERE conversation_id = $1
    AND user_id = $2
)
`

type IsConversationMemberParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMessages = `-- name: ListMessages :many
SELECT
    m.id,
    m.conversation_id,
    m.sender_id,
    m.content,
    m.created_at,

    p.username,
    p.display_name,
    p.avatar_url

FROM messages m

JOIN profiles p
    ON p.user_id = m.sender_id

WHERE m.conversation_id = $1

ORDER BY m.created_at ASC
LIMIT $2
`

type ListMessagesParams struct {
	ConversationID pgtype.UUID
	Limit          int32
}

type ListMessagesRow struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	SenderID       pgtype.UUID
	Content        string
	CreatedAt      pgtype.Timestamptz
	Username       string
	DisplayName    string
	AvatarUrl      pgtype.Text
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
