// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message_reads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMessageReaders = `-- name: GetMessageReaders :many
SELECT
    user_id,
    read_at
FROM message_reads
WHERE message_id = $1
`

type GetMessageReadersRow struct {
	UserID pgtype.UUID
	ReadAt pgtype.Timestamptz
}

func (q *Queries) GetMessageReaders(ctx context.Context, messageID pgtype.UUID) ([]GetMessageReadersRow, error) {
	rows, err := q.db.Query(ctx, getMessageReaders, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageReadersRow
	for rows.Next() {
		var i GetMessageReadersRow
		if err := rows.Scan(&i.UserID, &i.ReadAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageRead = `-- name: MarkMessageRead :exec
INSERT INTO message_reads (
    message_id,
    user_id
)
VALUES (
    $1,
    $2
)
ON CONFLICT (message_id, user_id)
DO UPDATE SET
    read_at = NOW()
`

type MarkMessageReadParams struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) error {
	_, err := q.db.Exec(ctx, markMessageRead, arg.MessageID, arg.UserID)
	return err
}
