// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID          pgtype.UUID
	MessageID   pgtype.UUID
	Type        string
	Filename    pgtype.Text
	MimeType    pgtype.Text
	Size        pgtype.Int8
	StorageKey  pgtype.Text
	ExternalUrl pgtype.Text
	Metadata    []byte
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
}

type Conversation struct {
	ID        pgtype.UUID
	Type      string
	CreatedAt pgtype.Timestamptz
}

type ConversationMember struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
	JoinedAt       pgtype.Timestamptz
}

type Message struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	SenderID       pgtype.UUID
	Content        string
	CreatedAt      pgtype.Timestamptz
}

type MessageDelivery struct {
	MessageID   pgtype.UUID
	UserID      pgtype.UUID
	DeliveredAt pgtype.Timestamptz
}

type MessageRead struct {
	MessageID pgtype.UUID
	UserID    pgtype.UUID
	ReadAt    pgtype.Timestamptz
}

type Profile struct {
	UserID      pgtype.UUID
	Username    string
	DisplayName string
	Bio         pgtype.Text
	AvatarUrl   pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
