// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    user_id,
    username,
    display_name
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING user_id, username, display_name, bio, avatar_url, created_at, updated_at
`

type CreateProfileParams struct {
	UserID      pgtype.UUID
	Username    string
	DisplayName string
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.UserID, arg.Username, arg.DisplayName)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET
    display_name = $2,
    bio = $3,
    updated_at = NOW()
WHERE user_id = $1
RETURNING
    user_id,
    username,
    display_name,
    bio,
    avatar_url,
    created_at,
    updated_at
`

type UpdateProfileParams struct {
	UserID      pgtype.UUID
	DisplayName string
	Bio         pgtype.Text
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile, arg.UserID, arg.DisplayName, arg.Bio)
	var i Profile
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
